### ISSUE TITLE
PathTemplate not escaping separators in complex resource IDs

### ISSUE THREAD

**Issue by jedvardsson** [googleapis/api-common-java#367] opened 2022-09-01 13:34 UTC
PathTemplates using complex resource IDs does not escape complex separators.

The following code fails for version 2.2.1. 

#### Code example

```java
import com.google.api.pathtemplate.PathTemplate;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

class PathTemplateTest {
    
    @Test
    void test() {
        PathTemplate template = PathTemplate.create("resources/{foo}_{bar}");
        Assertions.assertEquals("resources/abc%5F123_def%5F456", template.instantiate("foo", "abc_123", "bar", "def_456"));
    }
}
```

#### Stack trace
```
org.opentest4j.AssertionFailedError: 
Expected :resources/abc%5F123_def%5F456
Actual   :resources/abc_123_def_456
```

**Comment by meltsufin** [comment] 2022-09-28 18:28
Are you assuming that they *should* be escaped? Is that documented behavior somewhere?

**Comment by meltsufin** [comment] 2022-09-28 18:33
Closing as "intended behavior". Please re-open if you disagree.

**Closed by meltsufin** 2022-09-28 18:33 UTC
Labels: type: question
